challenge_long_name: NEON Ecological Forecasting Challenge
project_id: neon4cast
endpoint: sdsc.osn.xsede.org
noaa_endpoint: s3.flare-forecast.org
submissions_endpoint: submit.ecoforecast.org
scores_bucket: bio230014-bucket01/challenges/scores
forecasts_bucket: bio230014-bucket01/challenges/forecasts
summaries_bucket: bio230014-bucket01/challenges/forecasts/summaries
submissions_bucket: submissions
inventory_bucket: bio230014-bucket01/challenges/inventory
noaa_forecast_bucket: drivers/noaa/gefs-v12-reprocess/
prov_bucket: bio230014-bucket01/challenges/prov
targets_bucket: bio230014-bucket01/challenges/targets
archive_bucket: bio230014-bucket01/challenges/archive
model_metadata_bucket: bio230014-bucket01/challenges/metadata/model_id
model_metadata_gsheet: https://docs.google.com/spreadsheets/d/1f177dpaxLzc4UuQ4_SJV9JWIbQPlilVnEztyvZE6aSU/edit?usp=sharing
example_model_id: example
site_path: 'catalog/sites'
site_table: neon4cast_field_site_metadata.csv
site_thumbnail: 'https://www.neonscience.org/sites/default/files/styles/max_2600x2600/public/2021-04/2021_04_graphic_Domain_Map_no-Titles-png.png?itok=7MsHPigZ'
site_thumbnail_title: "NEON Sites Map"
site_table_link: 'https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/neon4cast_field_site_metadata.csv'
target_metadata_gsheet: https://docs.google.com/spreadsheets/d/10YTX9ae_C1rFdLgEDkUcCRCpUkVYv06leY01BtD1BgM/edit?usp=sharing
targets_thumbnail: 'https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/catalog/thumbnail_plots/neon_stream.jpg'
targets_thumbnail_title: 'Test Image'
targets_path: 'catalog/targets/'
challenge_url: https://projects.ecoforecast.org/neon4cast-ci
github_repo: eco4cast/neon4cast-ci
target_groups:
  Aquatics:
    targets_file: "https://data.ecoforecast.org/neon4cast-targets/aquatics/aquatics-targets.csv.gz"
  Terrestrial:
    targets_file: "https://data.ecoforecast.org/neon4cast-targets/terrestrial/terrestrial-targets.csv.gz"
  Beetles:
    targets_file: "https://data.ecoforecast.org/neon4cast-targets/beetles/beetles-targets.csv.gz"
  Phenology:
    targets_file: "https://data.ecoforecast.org/neon4cast-targets/phenology/phenology-targets.csv.gz"
  Ticks:
    targets_file: "https://data.ecoforecast.org/neon4cast-targets/ticks/ticks-targets.csv.gz"
noaa_forecast_groups: ['Pseudo','Stage1-stats','Stage1','Stage2','Stage3']
noaa_forecast_group_paths: ['pseudo','stage1-stats','stage1','stage2','stage3']
variable_groups:
  Aquatics:
    variable: ['oxygen','temperature','chla']
    duration: ['P1D','P1D','P1D']
    thumbnail_link: 'https://projects.ecoforecast.org/neon4cast-catalog/img/neon_buoy.jpg'
    thumbnail_title: 'NEON Aquatics Buoy'
  Terrestrial:
    variable: ['nee','le','nee','le']
    duration: ['P1D','P1D','PT30M','PT30M']
    thumbnail_link: 'https://projects.ecoforecast.org/neon4cast-catalog/img/BONA_Twr.jpg'
    thumbnail_title: 'NEON Field Tower'
  Phenology:
    variable: ['gcc_90','rcc_90']
    duration: ['P1D','P1D']
    thumbnail_link: 'https://www.neonscience.org/sites/default/files/styles/max_1300x1300/public/image-content-images/_BFP8455.jpg'
    thumbnail_title: 'Phenology Image'
  Beetles:
    variable: ['abundance', 'richness']
    duration: ['P1W','P1W']
    thumbnail_link: 'https://www.neonscience.org/sites/default/files/styles/max_width_1170px/public/image-content-images/Beetles_pinned.jpg'
    thumbnail_title: 'Beetle Image'
  Ticks:
    variable: ['amblyomma_americanum']
    duration: ['P1W']
    thumbnail_link: 'https://www.neonscience.org/sites/default/files/styles/max_2600x2600/public/image-content-images/tick-image.jpg'
    thumbnail_title: 'NEON Ticks'
catalog_config:
  about_string: 'https://projects.ecoforecast.org/neon4cast-docs/'
  about_title: 'NEON Ecological Forecasting Challenge Documentation'
  scores_thumbnail: "https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/catalog/thumbnail_plots/52760199990_d1a0f154fe_c.jpg"
  scores_thumbnail_title: "NEON Buoy Image"
  forecasts_thumbnail: "https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/catalog/thumbnail_plots/51629805865_0ef01ffbbc_c.jpg"
  forecasts_thumbnail_title: "NEON Buoy Image"
  forecast_path: 'catalog/forecasts/'
  scores_path: 'catalog/scores/'
  summaries_path: 'catalog/summaries/'
  summaries_thumbnail: 'https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/catalog/thumbnail_plots/neon_desert.jpg'
  summaries_thumbnail_title: "NEON Image"
  inventory_path: 'catalog/inventory'
  inventory_thumbnail: 'https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/catalog/thumbnail_plots/neon_forest.jpg'
  inventory_thumbnail_title: "NEON Image"
  noaa_path: 'catalog/noaa_forecasts/'
  noaa_thumbnail: 'https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/catalog/thumbnail_plots/neon_wetland.jpg'
  noaa_thumbnail_title: "NEON Image"
  aws_download_path_forecasts: 'bio230014-bucket01/challenges/forecasts/parquet/'
  aws_download_path_scores: 'bio230014-bucket01/challenges/scores/parquet/'
  summaries_download_path: 'bio230014-bucket01/vera4cast/forecasts/summaries/parquet/'
  host_url: "https://www.ecoforecastprojectvt.org"
  host_name: "Ecoforecast Challenge"
  bbox:
    max_lat: 71.2824
    min_lat: 17.9696
    max_lon: -66.7987
    min_lon: -156.6194
  site_type: 'MultiPoint'
  base_image_path: 'https://data.ecoforecast.org/neon4cast-catalog'
  citation_doi: "https://doi.org/10.1002/fee.2616"
  citation_text: "Thomas, R.Q., C. Boettiger, C.C. Carey, M.C. Dietze, L.R. Johnson, M.A. Kenney, J.S. Mclachlan, J.A. Peters, E.R. Sokol, J.F. Weltzin, A. Willson, W.M. Woelmer, and Challenge Contributors. 2023. The NEON Ecological Forecasting Challenge. Frontiers in Ecology and Environment 21: 112-113."
  dashboard_url: "https://projects.ecoforecast.org/neon4cast-docs/"
  dashboard_title: "NEON Forecast Challenge Dashboard"
  site_metadata_url: 'https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/neon4cast_field_site_metadata.csv'
