# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  #schedule:
  #  - cron: '0 7 * * *'
  workflow_dispatch:

name: aquatics-target-generation

jobs:
  aquatics:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_SUBMISSIONS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SUBMISSIONS }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
      NEON_TOKEN: ${{ secrets.NEON_TOKEN }}
      EFI_NRP_KEY: ${{ secrets.EFI_NRP_KEY }}
      EFI_NRP_SECRET: ${{ secrets.EFI_NRP_SECRET }}
    container: eco4cast/rocker-neon4cast:latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt-get -y install python3-venv python3-pip python3-dev

      - name: Generate targets
        shell: Rscript {0}
        run: |
          source("targets/aquatics_targets.R")

 
