name: Disease Targets Download

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 12 * * *'  # runs at 12:00 UTC every day (~7 AM ET in standard time)

jobs:
  r-job:
    runs-on: ubuntu-latest

    env:
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
      GITHUB_PAT: ${{ secrets.MICRODATASUS_INSTALL_TEST }}

    container: eco4cast/rocker-neon4cast:latest

    steps:
     # 1. Checkout repository
      - uses: actions/checkout@v3
      
    # 2. Load Microdatasus
      - name: Install and load microdatasus
        run: |
          R -e "
            install.packages('remotes')
            remotes::install_github('rfsaldanha/microdatasus')
            library(microdatasus)
          "

      # 3. Run your script
      - name: Run Disease Targets Script
        run: |
          Rscript targets/disease_targets.R
