name: Disease Targets Download

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 12 * * *'  # runs at 12:00 UTC every day (~7 AM ET in standard time)

jobs:
  r-job:
    runs-on: ubuntu-latest

    env:
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
      MICRODATASUS_INSTALL: ${{ secrets.MICRODATASUS_INSTALL }}

    container: eco4cast/rocker-neon4cast:latest

    steps:
     # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Run your script
      - name: Run Disease Targets Script
        run: |
          Rscript targets/disease_targets.R
