# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

name: prep-scoring

jobs:
  scoring:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container:
      image: ghcr.io/boettiger-lab/k8s@sha256:fd02edfb4318afe022f8a732a99d93df7127dadb2bb4e208e36a86f96c2f45c6
      options: --user root
    steps:

      - name: cleanup disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h

      - uses: actions/checkout@v4

      - name: install
        run: R -e "install.packages(c('bench', 'duckdbfs', 'minioclient')); remotes::install_github('eco4cast/score4cast')"

      - name: scoring
        run: r scoring/prep-scoring.R
