# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

name: scoring

jobs:
  scores:
    runs-on:  arc-runner-set
    timeout-minutes: 1440
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container: eco4cast/rocker-neon4cast:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        shell: Rscript {0}
        run: |
          print(options("repos"))
          remotes::install_deps(".", dep=TRUE, upgrade=FALSE)
          
      - name: really-install
        shell: Rscript {0}
        run: remotes::install_github("cboettig/duckdbfs", upgrade=FALSE)

      - name: Generate scores
        shell: Rscript {0}
        run: |
          source("scoring/new-scoring.R")

  inventory:
    needs: scores
    runs-on:  arc-runner-set
    timeout-minutes: 1440
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container: eco4cast/rocker-neon4cast:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        shell: Rscript {0}
        run: |
          print(options("repos"))
          remotes::install_deps(".", dep=TRUE, upgrade=FALSE)

      - name: Update inventory
        shell: Rscript {0}
        run: |
          source("scoring/build_score_inventory.R")
